### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by dmulder** [SohamBhure/Q-Learning-In-C#1]
Your code has no license. I'm interested in including your implementation in the Samba project, but your project would need to be licensed as GPL-3. I'd gladly attribute your work if I'm able to use the code.

**Comment by dmulder** [comment]
Legally you've retained all rights to this code by not adding a license, see here:
https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license
Technically the only exception is a right to fork your code, which is a legal gray area.

**Comment by SohamBhure** [comment]
Hi David,
Will add the license in a few hours.

**Comment by dmulder** [comment]
Thanks!
